# Generated by Django 4.2.27 on 2026-01-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('source_app', models.CharField(blank=True, max_length=200, verbose_name='Application source')),
                ('activity_type', models.CharField(blank=True, max_length=200, verbose_name="Type d'activité")),
                ('activity_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'activité")),
                ('elapsed_time', models.DurationField(blank=True, null=True, verbose_name='Temps écoulé')),
                ('active_time', models.DurationField(blank=True, null=True, verbose_name='Temps actif')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distance (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='CaloriesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('calories', models.IntegerField(verbose_name='Calories')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée de calories',
                'verbose_name_plural': 'Entrées de calories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CardioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('treadmill_minutes', models.IntegerField(default=0, verbose_name='Marche sur tapis (min)')),
                ('bike_minutes', models.IntegerField(default=0, verbose_name='Vélo (min)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée de cardio',
                'verbose_name_plural': 'Entrées de cardio',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GymSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Séance de salle',
                'verbose_name_plural': 'Séances de salle',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (kg)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% de graisse corporelle')),
                ('fat_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masse grasse')),
                ('fat_free_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% sans gras')),
                ('fat_free_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masse sans graisse')),
                ('skeletal_muscle_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% muscle squelettique')),
                ('skeletal_muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masse musculaire squelettique')),
                ('muscle_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% de masse musculaire')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masse musculaire')),
                ('bone_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masse osseuse')),
                ('total_body_water', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eau corporelle totale')),
                ('basal_metabolic_rate', models.IntegerField(blank=True, null=True, verbose_name='Taux métabolique de base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée de poids',
                'verbose_name_plural': 'Entrées de poids',
                'ordering': ['-date', '-time'],
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='StepsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('steps', models.IntegerField(verbose_name='Nombre de pas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée de pas',
                'verbose_name_plural': 'Entrées de pas',
                'ordering': ['-date', '-time'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
