# Generated by Django 4.2.27 on 2026-01-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioentry',
            name='speed',
            field=models.FloatField(default=4.0, verbose_name='Vitesse (km/h)'),
        ),
    ]
