# Generated by Django 4.2.27 on 2026-01-08 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_cardioentry_speed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityentry',
            options={'ordering': ['-date'], 'verbose_name': "Entrée d'activité", 'verbose_name_plural': "Entrées d'activité"},
        ),
        migrations.AlterModelOptions(
            name='stepsentry',
            options={'ordering': ['-date'], 'verbose_name': 'Entrée de pas', 'verbose_name_plural': 'Entrées de pas'},
        ),
        migrations.AlterModelOptions(
            name='weightentry',
            options={'ordering': ['-date'], 'verbose_name': 'Entrée de poids', 'verbose_name_plural': 'Entrées de poids'},
        ),
        migrations.AlterUniqueTogether(
            name='stepsentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weightentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gymsession',
            name='session_type',
            field=models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('UPPER', 'Upper Body'), ('LOWER', 'Lower Body'), ('CARDIO', 'Cardio')], default='PUSH', max_length=10, verbose_name='Type de séance'),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='visceral_fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Graisse viscérale'),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='active_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps actif (s)'),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='activity_name',
            field=models.CharField(max_length=200, verbose_name="Nom de l'activité"),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='activity_type',
            field=models.CharField(max_length=100, verbose_name="Type d'activité"),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='elapsed_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps écoulé (s)'),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='source_app',
            field=models.CharField(max_length=100, verbose_name='Application source'),
        ),
        migrations.AlterField(
            model_name='activityentry',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure'),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stepsentry',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stepsentry',
            name='steps',
            field=models.IntegerField(verbose_name='Pas'),
        ),
        migrations.AlterField(
            model_name='stepsentry',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='basal_metabolic_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Métabolisme de base (kcal)'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Graisse corporelle (%)'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masse musculaire (kg)'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='muscle_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Muscle (%)'),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure'),
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='bone_mass',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='fat_free_mass',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='fat_free_percentage',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='fat_mass',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='skeletal_muscle_mass',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='skeletal_muscle_percentage',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='total_body_water',
        ),
    ]
