# Generated by Django 4.2.27 on 2026-01-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_activityentry_options_alter_stepsentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCalorieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suivi journalier',
                'verbose_name_plural': 'Suivis journaliers',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('serving_size', models.IntegerField(default=100, verbose_name='Portion (g)')),
                ('calories', models.IntegerField(verbose_name='Calories')),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Protéines (g)')),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Glucides (g)')),
                ('fat', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Lipides (g)')),
                ('is_custom', models.BooleanField(default=True, verbose_name='Personnalisé')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Code-barres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aliment',
                'verbose_name_plural': 'Aliments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du repas type')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Petit-déjeuner'), ('SNACK_AM', 'Collation matin'), ('LUNCH', 'Déjeuner'), ('SNACK_PM', 'Collation après-midi'), ('DINNER', 'Dîner')], default='LUNCH', max_length=20, verbose_name='Type de repas suggéré')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Repas type',
                'verbose_name_plural': 'Repas types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Quantité (portions)')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.food', verbose_name='Aliment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_items', to='tracker.mealtemplate', verbose_name='Repas type')),
            ],
            options={
                'verbose_name': 'Élément de repas type',
                'verbose_name_plural': 'Éléments de repas type',
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Petit-déjeuner'), ('SNACK_AM', 'Collation matin'), ('LUNCH', 'Déjeuner'), ('SNACK_PM', 'Collation après-midi'), ('DINNER', 'Dîner')], max_length=20, verbose_name='Type de repas')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Quantité (portions)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tracker.dailycalorieentry', verbose_name='Entrée journalière')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.food', verbose_name='Aliment')),
            ],
            options={
                'verbose_name': 'Élément de repas',
                'verbose_name_plural': 'Éléments de repas',
                'ordering': ['meal_type', 'created_at'],
            },
        ),
    ]
