# Generated by Django 4.2.27 on 2026-01-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_dailycalorieentry_food_mealtemplate_mealtemplateitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Fibres (g)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal_type',
            field=models.CharField(choices=[('LUNCH', 'Déjeuner'), ('SNACK_AM', 'Collation'), ('DINNER', 'Dîner'), ('SNACK_PM', 'Collation')], max_length=20, verbose_name='Type de repas'),
        ),
        migrations.AlterField(
            model_name='mealtemplate',
            name='meal_type',
            field=models.CharField(choices=[('LUNCH', 'Déjeuner'), ('SNACK_AM', 'Collation'), ('DINNER', 'Dîner'), ('SNACK_PM', 'Collation')], default='LUNCH', max_length=20, verbose_name='Type de repas suggéré'),
        ),
    ]
