# Generated by Django 4.2.27 on 2026-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_food_fiber_alter_mealitem_meal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('category', models.CharField(help_text='Ex: Fruits, Légumes, Viandes, etc.', max_length=100, verbose_name='Catégorie')),
                ('calories', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Calories (kcal/100g)')),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Protéines (g/100g)')),
                ('carbs', models.DecimalField(decimal_places=1, help_text='Glucides disponibles (convention EU)', max_digits=5, verbose_name='Glucides (g/100g)')),
                ('fat', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Lipides (g/100g)')),
                ('fiber', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Fibres (g/100g)')),
                ('unit_weight', models.DecimalField(decimal_places=2, help_text="Poids moyen d'une unité (ex: 120g pour une banane)", max_digits=7, verbose_name='Poids unitaire (g)')),
                ('ciqual_code', models.CharField(blank=True, help_text="Code de l'aliment dans la base CIQUAL", max_length=50, null=True, verbose_name='Code CIQUAL')),
                ('ciqual_name', models.CharField(blank=True, help_text='Nom exact dans CIQUAL', max_length=300, null=True, verbose_name='Nom CIQUAL')),
                ('data_source', models.CharField(default='CIQUAL 2020', max_length=100, verbose_name='Source des données')),
                ('last_verified', models.DateField(auto_now=True, verbose_name='Dernière vérification')),
                ('keywords', models.TextField(help_text='Mots-clés de recherche séparés par des virgules', verbose_name='Mots-clés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aliment générique',
                'verbose_name_plural': 'Aliments génériques',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['name'], name='tracker_gen_name_bae1eb_idx'), models.Index(fields=['category'], name='tracker_gen_categor_c936e3_idx')],
            },
        ),
    ]
