# Generated by Django 4.2.27 on 2026-01-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_genericfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenFoodFactsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code-barres')),
                ('product_name', models.CharField(db_index=True, max_length=500, verbose_name='Nom du produit')),
                ('brands', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Marques')),
                ('energy_kcal_100g', models.FloatField(blank=True, null=True, verbose_name='Énergie (kcal/100g)')),
                ('proteins_100g', models.FloatField(blank=True, null=True, verbose_name='Protéines (g/100g)')),
                ('carbohydrates_100g', models.FloatField(blank=True, null=True, verbose_name='Glucides (g/100g)')),
                ('fat_100g', models.FloatField(blank=True, null=True, verbose_name='Lipides (g/100g)')),
                ('fiber_100g', models.FloatField(blank=True, null=True, verbose_name='Fibres (g/100g)')),
                ('countries', models.CharField(blank=True, max_length=500, verbose_name='Pays')),
                ('categories', models.CharField(blank=True, max_length=1000, verbose_name='Catégories')),
                ('last_modified', models.DateTimeField(blank=True, null=True, verbose_name='Dernière modification OFF')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Produit Open Food Facts',
                'verbose_name_plural': 'Produits Open Food Facts',
                'db_table': 'tracker_openfoodfacts_product',
                'ordering': ['product_name'],
                'indexes': [models.Index(fields=['product_name'], name='tracker_ope_product_c63ad9_idx'), models.Index(fields=['brands'], name='tracker_ope_brands_6cfeb4_idx'), models.Index(fields=['code'], name='tracker_ope_code_4b277f_idx')],
            },
        ),
    ]
