# Generated by Django 4.2.27 on 2026-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_openfoodfactsproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealitem',
            options={'ordering': ['meal_type', 'order', 'created_at'], 'verbose_name': 'Élément de repas', 'verbose_name_plural': 'Éléments de repas'},
        ),
        migrations.AddField(
            model_name='mealitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
    ]
