# Generated by Django 4.2.27 on 2026-01-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_mealitem_options_mealitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='body_water',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eau corporelle (kg)'),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='bone_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masse osseuse (kg)'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Petit-déjeuner'), ('LUNCH', 'Déjeuner'), ('SNACK_AM', 'Collation 1'), ('DINNER', 'Dîner'), ('SNACK_PM', 'Collation 2')], max_length=20, verbose_name='Type de repas'),
        ),
        migrations.AlterField(
            model_name='mealtemplate',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Petit-déjeuner'), ('LUNCH', 'Déjeuner'), ('SNACK_AM', 'Collation 1'), ('DINNER', 'Dîner'), ('SNACK_PM', 'Collation 2')], default='LUNCH', max_length=20, verbose_name='Type de repas suggéré'),
        ),
    ]
